### ISSUE TITLE
能否考虑将Watch和Fork的情况一起算入被偷心

### ISSUE THREAD

**Issue by LaoshuBaby** [RimoChan/steal_piano#1]
众所周知，Star只算点赞，Fork了还PR才是真正的表白（狗头

如果哪个Loli已经Watch你的话，一定是动心了吧（疯狂狗头

**Comment by RimoChan** [comment]
我昨天看了一下github的api，不是所有数据都有时间戳，比如star有，follow就没有，所以fork和watch不一定能做……

**Comment by LaoshuBaby** [comment]
唔，那就挠头了（惨啊




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年4月5日(星期一) 晚上9:22
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [RimoChan/steal_piano] 能否考虑将Watch和Fork的情况一起算入被偷心 (#1)





 
我昨天看了一下github的api，不是所有数据都有时间戳，比如star有，follow就没有，所以fork和watch不一定能做……
