### ISSUE TITLE
api rate limit exceeded

### ISSUE THREAD

**Issue by takayama-lily** [RimoChan/steal_piano#3]
star比较多的情况下(5k+大概1w不到)出现如下情况，算是不可抗力嘛
![image](https://user-images.githubusercontent.com/12014361/113642012-bf727e80-96b9-11eb-8219-5be1f013493f.png)

**Comment by RimoChan** [comment]
嗯……硬盘有缓存，问题不大，你过1个小时再重试应该就可以刷完了……

**Comment by chenxuuu** [comment]
dc这个文件夹能自动新建一个不，我看默认直接保存失败来着

**Comment by RimoChan** [comment]
> dc这个文件夹能自动新建一个不，我看默认直接保存失败来着

有了有了
